### ISSUE TITLE
Request - WiFi

### ISSUE THREAD

**Issue by MFernstrom** [michael-ring/pico-fpcexamples#6]
Are there any plans to support the Wireless functionality on the Pico W?
Is it something that could be donated for?

**Comment by michael-ring** [comment]
I am not taking donations as this a pure hobby for me, thank you for the offer anyway.
I am looking into WiFi but so far I have not succeded and I am thinking about integrating FreeRTOS as well because for anything than very simple GET requests we will likely need async tasks anyway and for stuff like this FreeRTOS is the way to go. 
Closing for now, will reopen when I see the light at the end of the tunnel.
